module.exports = {
  'arrow-parens': ['error', 'always'],
  'arrow-spacing': ['error', { before: true, after: true }],
  'comma-dangle': ['error', {
    arrays: 'always-multiline',
    objects: 'always-multiline',
    imports: 'always-multiline',
    exports: 'always-multiline',
    functions: 'only-multiline',
  }],
  'comma-spacing': ['error', { before: false, after: true }],
  'consistent-return': ['off'],
  'eol-last': ['error'],
  'func-call-spacing': ['error', 'never'],
  'function-paren-newline': ['error', 'multiline-arguments'],
  'indent': ['error', 2, { SwitchCase: 1, ignoredNodes: ['JSXElement'] }],
  'jsx-quotes': ['error', 'prefer-single'],
  'key-spacing': ['error', { beforeColon: false, afterColon: true }],
  'keyword-spacing': ['error', { before: true, after: true }],
  'no-multiple-empty-lines': ['error', { max: 1 }],
  'no-trailing-spaces': ['error'],
  'no-underscore-dangle': ['off'],
  'object-curly-spacing': ['error', 'always'],
  'object-property-newline': ['error', { allowMultiplePropertiesPerLine: true }],
  'padded-blocks': ['error', 'never'],
  'padding-line-between-statements': [
    'error',
    { blankLine: 'always', prev: ['const', 'let', 'var'], next: '*' },
    { blankLine: 'any', prev: ['const', 'let', 'var'], next: ['const', 'let', 'var'] },
  ],
  'prefer-template': ['error'],
  'quotes': ['error', 'single', { allowTemplateLiterals: true }],
  'quote-props': ['error', 'consistent-as-needed'],
  'semi': ['error', 'never'],
  'semi-spacing': ['error', { before: false, after: true }],
  'space-infix-ops': ['error'],
  'template-curly-spacing': ['error', 'never'],

}
